### ISSUE TITLE
Seek to video NOK

### ISSUE THREAD

**Issue by adjouhri** [Orange-OpenSource/hasplayer.js#10]
Hi,

I manage to play a video with an Akamai secure HD token, adding withCredentials = true to the manifest and fragment request (ManifestLoader & CustomFragmentLoader).

Now, I'm trying to seek to this video, but it fails.
I'm debugging it since two days and I'm blocked. I hope you can help on that, or give me some advise.

Here is the url of the video : 
http://catchup-smooth.eurosport.com/eurosport2_france/203_20150416T195635-20150416T205450/manifest.ism/Manifest?hdnea=st=1422443644~exp=1431083644~acl=*~hmac=45d2ddb2427ce9b387250af24823879b46a38da240753961ce597142e27630a1

When i do a seek (video.currentTime = mySeekTime), I can see on the log that the fragment are loaded in background, but the video stay blocked.

For example, when I seek to 150s, it request the fragment up to 165.2

[BufferController][video] loadNextFragment for time: 150
[DashHandler][video] Getting the request for time: 150
[DashHandler][video] getIndexForSegments for time  150
[DashHandler][video] getIndexForSegments, idx =   74
[DashHandler][video] Index for time 150 is 74

[...]

[BufferController][video] loadNextFragment for time: 165.2
[DashHandler][video] Getting the request for time: 165.2
[DashHandler][video] getIndexForSegments for time  165.2
[DashHandler][video] getIndexForSegments, idx =   82
[DashHandler][video] Index for time 165.2 is 82
SegmentTimeline: 163.7 / 3495.8930158
[BufferController][video] ### Load request  http://catchup-smooth.eurosport.com/eurosport2_france/203_20150416T195635-2…0416T205450/manifest.ism/QualityLevels(1802000)/Fragments(video=1652000000)
[FragmentLoader][video] Load: http://catchup-smooth.eurosport.com/eurosport2_france/203_20150416T195635-2…0416T205450/manifest.ism/QualityLevels(1802000)/Fragments(video=1652000000)
[FragmentLoader][video] Loaded: http://catchup-smooth.eurosport.com/eurosport2_france/203_20150416T195635-2…0416T205450/manifest.ism/QualityLevels(1802000)/Fragments(video=1652000000) (200, 2ms, 2ms)
[BufferController][video] ### Media loaded  http://catchup-smooth.eurosport.com/eurosport2_france/203_20150416T195635-2…0416T205450/manifest.ism/QualityLevels(1802000)/Fragments(video=1652000000)
[BufferController][video] ### Buffer segment from url  http://catchup-smooth.eurosport.com/eurosport2_france/203_20150416T195635-2…0416T205450/manifest.ism/QualityLevels(1802000)/Fragments(video=1652000000)
[BufferController][video] Buffering segment
[BufferController][video] ### Buffered video range [0]: 1.5 - 21.5 (150)
[BufferController][video] ### Buffered video range [1]: 149.200011 - 167.2 (150)
[BufferController][video] ### Media segment buffered
[BufferController][video] checkIfSufficientBuffer
[BufferController][video] Buffer level = 17.19999999999999
[BufferController][audio] checkIfSufficientBuffer
[BufferController][audio] Buffer level = 0
[BufferController][video] checkIfSufficientBuffer
[BufferController][video] Buffer level = 17.19999999999999
[BufferController][audio] checkIfSufficientBuffer
[BufferController][audio] Buffer level = 0

And then, it loop indefinitely on checkIfSufficientBuffer and updateBufferLevel.

Regards,
Abel

**Comment by bbert** [comment]
Hi,

Looking at the logs, seek seems to be correctly handled at buffer controller level, but the problem comes from the <video> controller which do not play after seeking, since currentTime stays at 150.
If buffer controller requests up to 165.2, that's for filling the buffer (up to 16 seconds).
Now we have to find the reason why the <video> do not play after seeking, moreover since buffer range seems to be OK (149.200011 - 167.2).

I cannot test the url you provided since I get the error: "An error occurred while processing your request."

Maybe you could provide the whole logs, this could help.

Regards,
Bertrand

**Comment by adjouhri** [comment]
Hi Bertrand,

Thank you for your quick answer.

Here is another video which is avaiable :
http://catchup-smooth.eurosport.com/eurosport_france/3_20150421T221839-20150421T225528/manifest.ism/Manifest?hdnea=st=1422443644~exp=1431083644~acl=*~hmac=45d2ddb2427ce9b387250af24823879b46a38da240753961ce597142e27630a1

You can find attached the complete file of the scenario:

1.       Playing the above url

2.       Waiting for ~6s

3.       Seek to 150


Regards,
Abel

**Comment by bbert** [comment]
I tried your stream with chrome and IE11/W8.1 on a PC desktop and it works.
Which browser/platform do you use?

However I notice another problem with your stream: there is a difference between the timestamps of the audio fragments in the manifest and the real timestamps of the fragments that are pushed into the buffers. This results, when switching audio bitrate, in downloading two consecutive segments of different bitrate but with same timestamp.

**Comment by adjouhri** [comment]
I’m using chrome 39 on a Win7 PC. I’ve got the same issue on chrome 42.
Nothing work on IE11…


But the seek works fine with one of your video example:
http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest

Maybe an incompatibility with windows 7 and my video…?

Abel

**Comment by adjouhri** [comment]
I've tested chrome on a Win8.1, I have the same issue.

Maybe it comes from my code, but I modified only few things on the 1.1.0 version.
Just the withCredentials set to true to manage the token.

Are you testing a new version ?

**Comment by bbert** [comment]
I do use development version.
We should release a stable 1.2.0 version soon.

**Comment by adjouhri** [comment]
Hi again,

I hoped that a good night's sleep would help me find a solution, but... always not :(

I think that there is a problem on my side because you can seek to my video.
So, here is what I've done :
1. Download the sources on here on github, to test the same version as you.
2. Go to the page /samples/demoplayer/index.html
3. Test a video non secuized (to make no changes on the code) : 
/samples/demoplayer/index.html?url=http://instantreplay.eurosport.com/eurosport2_bundesliga/250_20150419T170431-20150419T170538/manifest.ism/Manifest
4. Seek to a position near the end of the video ~1m
5. I have again the same issue, it loop on the method checkIfSufficientBuffer

The thing is, when I seek back to ~10s, it plays the video, and when I seek again on ~1m then the seek works and the video is playing....
I feel that when I seek to a position whose video fragements are not on the buffer yet, it fails. But if I came back on this position a second time, it works.

Do you have any logical explaination on my problem ?


Thank you.

Regards,
Abel

**Comment by bbert** [comment]
Also you can directly test with the automatically compiled version of the 'development' branch, available here:
http://orange-opensource.github.io/hasplayer.js/1.2.0_dev/player.html
But it should give you the same result as with the version from the sources (of 'development' branch).
I also tested with version 1.1.0 (from 'master' branch), and indeed I notice the problem you described.
Did you really checkout the 'development' branch?

**Comment by adjouhri** [comment]
Ok it seems that I have different problems :

1. I can seek to a secure video (catchup) with the demoplayer in the samples folder.
But when I seek with my own page (based on demoplayer), the seek fails. My function just set the currentime. (Just like the demoplayer bu without a seekbar, I have an input text instead, in which I enter the number of seconds)
               // Seek on a position to a video
		function SeekVideo(){
				video.currentTime = document.getElementById("txt_seekvideo").value;
		}

2. I can't seek to a non secure video (instant replay)

3. I can't play the HD bitrate (2500) of a live video. The live starts to play on the minimum bitrate, and when it reach the maximum, it fails. Just like the seek of a video, it loop on checkIfSufficientBuffer.


It seems that for the problems 2 & 3, it is the currentTime which does not increment.

Which class manage the currentTime ? What is the entry point to debug this ?

Thank you,
Abel

**Comment by adjouhri** [comment]
I found something weird about the problem 1.
When I seek to a number of seconds finishing by 0, it fails (100, 1000,1110...), but when I seek to a number of seconds finishing by another number, it works (101, 1001,1111...

This is why the seek works with the timeline and can fail with an input text.

But, why do we have this disturbing behavior ?

**Comment by bbert** [comment]
I tried also to seek programmatically, and I have no problem, whatever the timestamp.
You have to set the currentTime attribute of the <video> component, the one who is attached to the MediaPlayer (see attachView).

**Comment by qchroman** [comment]
Did you guys get any further with this issue? Was it resolved?

Thank you.

**Comment by adjouhri** [comment]
HI, 
Yes it is resolved now.
To old to tell you how :)

**Comment by qchroman** [comment]
The reason I asked is because I see some strange behavior on one of my smooth streaming assets. The player comes to the following point

[15:15:54.796][BufferController][video] Buffer level = 0 (time:48.869003) 

and then simply updates the buffer over and over and over again w/o playing forward. The buffer, thought, has enough data cached as I understand (I only started debugging)

[15:15:54.795][BufferController][video] ### Buffered video range [0]: 0 - 48.84 (48.869003) 
keyos.mss.player.202.128.203.25.js:17 [15:15:54.795][BufferController][video] ### Buffered video range [1]: 49.24 - 68.32 (48.869003) 
keyos.mss.player.202.128.203.25.js:17 [15:15:54.795][BufferController][video] ### Buffered video range [2]: 68.76 - 86.36 (48.869003) 

Or does it mean that it can't play because the current time is 48.86 and there is no data buffered for it (0 - 48.84 and next 49.24 - 68.32)?

In any case, if video doesn't go out of buffer - player works great. If video does go out of buffered data, then player gets stuck for some reason. I use this player to test - https://github.com/Orange-OpenSource/hasplayer.js/tree/v1.2.1, May be I should try the development branch.

**Comment by qchroman** [comment]
Does it matter for the player whether the biggest bitrate in the manifest has index 0 or 4 (if there are 4 bitrates available)?

**Comment by bbert** [comment]
It seems that you have some gaps in your buffer, i.e. some discontinuities in your input stream.
For example, no data between timestamps 48.84 and 49.24.
That should explain the issue.

BTW, you can try with latest version.

**Comment by qchroman** [comment]
Thank you @bbert, that's what I'm doing now :)

**Comment by qchroman** [comment]
@bbert, unfortunately the issue is the same. I can post part of the log here for you to see if you like, sorry, I can't share the stream. The playback goes smooth until some moment when the playback simply stops. The data seems to be available in the buffer, but video buffer seems fragmented (unlike the audio buffer). May be when player tries to play some specific part of the video which is not in the buffer it stucks?

It should be fairly easy to replicate with Fiddler, for example, return 404 for some chunks to make the video buffer fragmented (just an idea)

**Comment by qchroman** [comment]
One question. Does this mean that there are 3 elements in the buffer or does this show us the time segments for different bitrates (0, 1 or 2)?

[19:07:44.092][BufferController][video] Buffered range [0]: 0 - 48.84 (48.912019) 
[19:07:44.093][BufferController][video] Buffered range [1]: 49.24 - 68.32 (48.912019) 
[19:07:44.093][BufferController][video] Buffered range [2]: 68.76 - 97.2 (48.912019)
