### ISSUE TITLE
Integrate back into Dash.JS

### ISSUE THREAD

**Issue by danrossi** [Orange-OpenSource/hasplayer.js#102]
Hi there this is a great project. However it's not an extension of dash.js it's using a very old codebase making it impossible to integrate back into it. 

What would be good is to use the ES6 code style and monkey patch import whatever is needed. It might help for maintainability rather than updating and modifying an old code base correct ? 

I don't believe then either the dash changes needed to be included here. It would be also good to then build without HLS support as HLS.JS can handle that. 

Just smoothstreaming changes I guess ?

**Comment by bbert** [comment]
Hi,
It is an extension of dash.js but of an old version of dash.js. At a certain point, it was difficult and then impossible to keep synchronized with dash.js, since it has been hugely refactored and, as you mentionned, it has also migrated to ES6.
Our initial intention was to support already deployed formats (SS and HLS) additionnaly to DASH in order to facilitate migration to DASH for service providers.
Also, having only one player supporting all formats avoid to have different player integration, with different APIs, into applications.
The ideal solution would be to resynchronize with dash.js and we are thinking about that.

**Comment by danrossi** [comment]
It might be easier to import patched files so everything else is included externally. I believe that is possible with ES6.

**Comment by eiximenis** [comment]
Hi,
I am *hugely* interested in integrating back with the new dashjs version. In fact i am doing some experimental tests about it.

IMHO hasplayer should be a "pure fork" of dashjs and should try to keep itself synchronized to the latest version of dashjs.

@bbert if this is something that you are planning to do in the short-time, i will gladly help if possible!

**Comment by danrossi** [comment]
I might look at helping out also but we would have no idea what is patched. That is why I think use the project externally and monkey patch imports using ES6. So I don't believe it has to fork anything if my suspicions are correct. 

I'm also providing the Flash fallback option for SmoothStreaming but that doesn't support PlayReady but then again neither will most of the browsers so it requires different sources ! 

Unfortunately dash.js is not setup as a "driver" based framework to pick and choose streaming controllers. I do like there is an option to only compile in smoothstreaming as that is all I'm interested in and provide dash in a separate file altogether.

**Comment by bbert** [comment]
FYI, we have started to integrate smooth streaming support into current version of dash.js.
Current version of dash.js already supports static (VOD) smooth streaming streams.
