### ISSUE TITLE
Is DRM Protected MPEG-DASH supported?

### ISSUE THREAD

**Issue by qchroman** [Orange-OpenSource/hasplayer.js#103]
Hello all,

Please, let me know if DRM protected MPEG-DASH assets are supported. It seems that it's not.

Thank you.

**Comment by squapp** [comment]
For pure DRM-protected MPEG DASH playback you should have a look at [dash.js](https://github.com/Dash-Industry-Forum/dash.js) or [shaka-player](https://github.com/google/shaka-player)

hasplayer.js is meant for playback of Smooth Streaming and HLS media formats

**Comment by bbert** [comment]
Hi,
hasplayer.js is not only meant for playback of Smooth Streaming and HLS. Since it based on dash.js, it can also playback DASH streams.
However, as I mentionned in issue #102, hasplayer.js has not been synchronized with dash.js for a long time and we haven't performed many tests on DASH streams.
But theoretically it does support DRM-protected DASH streams.

**Comment by qchroman** [comment]
@squapp, @bbert, thank you guys for such a quick answer. Yeah, I guess that because it's based on older version of dash.js you need to jump through some hoops to make the MPEG-DASH (DRM protected) play. It seems that hasplayer doesn't work with initData provided by the video element and PSSH boxes in it when it requests a key and uses initData developer provides himself using different protection models (ProtectionModel_3Feb2014, ProtectionModel_21Jan2015 etc...). Anyhow, thank you for the answer.

Have a great day.
