### ISSUE TITLE
MSS stream not playing

### ISSUE THREAD

**Issue by JobaDiniz** [Orange-OpenSource/hasplayer.js#12]
Hi, we develop a web app for Hungary, and the content provider claims some streams are not playing in our player correctly (HasPlayer).

They provided a test url, which does not play indeed: http://chkhu.connectmedia.hu/9912/stream0052.isml/Manifest (tested [here](http://orange-opensource.github.io/hasplayer.js/1.1.0/dashif.html))

However, the same stream works on Silverlight player: http://web12.connectmedia.hu/test/0052.html (embedded)

**Comment by bbert** [comment]
Hi,

Indeed, this streams does not play with current version of hasplayer.js.
The reason is that when audio fragments are pushed into the sourceBuffer, this SourceBuffer always remains empty.
Therefore, play never starts since we wait for some audio and video data to be pushed into the buffers before starting to play.
Now, what we need to identify is why the audio SourceBuffer remains empty. Maybe an issue with encoding and/or format. Maybe some unconformity between format description in manifest and segments data format?
We will try investigate.

**Comment by bbert** [comment]
Question: on which browser your streams are not playing?

**Comment by JobaDiniz** [comment]
Chrome

**Comment by JobaDiniz** [comment]
Hi, have you had a chance to look into this?

**Comment by bbert** [comment]
Hi,

Is this issue (audio decoding?) resolved?
