### ISSUE TITLE
MSS issue:  Video does not scale correctly at end of video 

### ISSUE THREAD

**Issue by ireneng** [Orange-OpenSource/hasplayer.js#122]
Hi hasplayer devs,

When I play a MSS video til the end and then click on fullscreen, the video does not scale correctly.
The video will remain the normal size.  I also found the issue to happen when you are watching a video in fullscreen as well.  Below are the steps to reprod the issue in your demo players.

Steps to reprod scaling issue in normal mode:
1. Using Edge, go to http://orange-opensource.github.io/hasplayer.js/dev/samples/Dash-IF/index.html
2. Select a MSS stream. For eg. VOD Superspeedway and click Load
3. Scrub to the end of the video
4. Click the fullscreen button - notice the video does not scale

Steps to reprod scaling issue in fullscreen:
1. Using Edge, go to http://orange-opensource.github.io/hasplayer.js/dev/samples/Dash-IF/index.html
2. Select a MSS stream. For eg. VOD Superspeedway and click Load
3. Go fullscreen
4. Scrub to the end of the video
5. Exit out of fullscreen - notice the video still takes up the whole screen.

I've tested this using the latest dev and release branches with my code. This issue appears to persist in both branches. Any help on this issue is greatly appreciated. 

Thanks!

**Comment by bbert** [comment]
Hi,
I think this problem is related to Edge (and IE11) but not to hasplayer.js.
I notice the same issue with dash.js player.
What I notice is that when you scrub to the end of the video, Edge executes multiple (indefinitely) seeks to the end of the video at the same timestamp, even if video is seeked to this timestamp.
On chrome and firefox it seems there is no similar issue.
