### ISSUE TITLE
License Persistency

### ISSUE THREAD

**Issue by qchroman** [Orange-OpenSource/hasplayer.js#145]
Hello!

In your latest player you have:

* Implements license persistence at application layer (protection model 21Jan2015) according to player configuration (by default no license persistence)

May I ask to clarify this a bit? Does it mean that persistent license is now available i.e. persistent license (PR, WV ?) can be acquired and w/o closing the browser end user may go offline and still playback the asset? What did you mean by saying "according to player configuration"?

Thank you very much in advance!

**Comment by bbert** [comment]
Hello,

We had implemented in v1.2.6 license persistency at application layer (i.e. hasplayer.js layer) in order to not request a license for a KID for which the player had already received a (valid) license.

Previously to 1.2.6 version, the ProtectionModel_21Jan2015 (and then its MediaKeys instance) was (re)created for each loaded stream,  reseting all previously acquired licences.

Since version 1.2.6, the ProtectionModel_21Jan2015 is created as a singleton, and then keeps the already loaded licenses information (initData) so that the player do not request the license for already stored licenses.

For some use cases, this functionnality is interesting (for example live zapping with long-time licences).
But in other uses cases, it may be required to always requesting a new licence. That's why we added this parameter.

But unfortunately, no, this is not for offline playing.

Hope this clarifies understanding

**Comment by qchroman** [comment]
Thank you, Bertrand!

It does. You mentioned the parameter. What parameter you refer to?

Thank you, again, for the quick answer!

BR

**Comment by bbert** [comment]
Hi,
The parameter is `Protection.licensePersistence`
See commit https://github.com/Orange-OpenSource/hasplayer.js/commit/32c0333b8240e31f171eed3632c71898c53f8dda .
By the way, the license persistence management in not fully functional in1.8.0.
Please refer to development branch until next version is released.

**Comment by qchroman** [comment]
Thank you!
