### ISSUE TITLE
SS playing, but duration value is wrong

### ISSUE THREAD

**Issue by JobaDiniz** [Orange-OpenSource/hasplayer.js#15]
Link: http://orange-opensource.github.io/hasplayer.js/1.2.0_dev/player.html?url=http://ireland1.cutvmanifest.api.ottcloudservices.com/smooth/Story4_SS/1432751700-1432761180/manifest

Why is the scrubber messed up?

**Comment by bbert** [comment]
Not sure to clearly understand your question. Did you mean that it takes long time until playing?
That is what I notice with this stream. One explanation is the xml to json conversion which takes about 6 seconds on my PC.
This is an issue we have planned to address in short time.

**Comment by JobaDiniz** [comment]
No, I meant that the *duration* returned is 1300 hours, which is clearly wrong. *Silverlight* player shows it right (same manifest)... Do you have an idea why *duration* is so wrong?

**Comment by bbert** [comment]
OK.
The problem comes from the media timestamps which do not start from 0 in this 'static' stream, and which is higher than the initial duration.
When the first fragment is pushed into the buffer, then the video component raises a durationchange event with a new duration that corresponds to the end of the buffer range since it is higher than the initial duration.
I do not know if this is the normal MSE behavior, but I notice the same behavior on IE and chrome.
I tried also playing with timestampOffset parameter of SouceBuffer object, but without success.

**Comment by kelvinoliveira** [comment]
I have the same problem. I tested in this version http://orange-opensource.github.io/hasplayer.js/1.2.1/player.html. Is there an update for this issue?

**Comment by bbert** [comment]
What is the issue? Which stream are you testing?

**Comment by JobaDiniz** [comment]
@bbert test here: http://orange-opensource.github.io/hasplayer.js/1.2.1/player.html?url=http://ireland1.cutvmanifest.api.ottcloudservices.com/smooth/Story4_SS/1444329000-1444331280/manifest *(this url will expire, comment here so I can update)*

The problem is that **duration** is wrong. I use Has-Player only for *live* streams, but now I'm testing _non-live_ streams and all of them return wrong **duration**.
