### ISSUE TITLE
Update Dash ?

### ISSUE THREAD

**Issue by adjouhri** [Orange-OpenSource/hasplayer.js#21]
Hi,

I would like to know if you have planned to update to dash 1.3 or 1.4 ?

Thanks.

Regards,
Abel

**Comment by bbert** [comment]
Hi,
For the time being no, due to lack of time.
There has been a huge refactoring in dash.js between 1.2 and 1.3, so the entire integration work has to be redone. Also, dash.js may evolve again in the future (refactoring by removing protocol's abstraction layer, ES6).
Our strategy as of today is to keep hasplayer.js as it is for playing MSS and HLS contents, and eventually take back some parts of source code from dash.js project, as we did recently with EME support stack. And then to progressively migrate to dash.js project for playing DASH contents.
