### ISSUE TITLE
MEDIA_ERR_DECODE for live streams

### ISSUE THREAD

**Issue by ivocarminati** [Orange-OpenSource/hasplayer.js#222]
Hi all, 

I'm having a problem when I try to stream live assets with Firefox browser (on Chrome all seems to work fine).
In particular, when I play the videoes randomly I receive the error below:

**VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support.
code: 3
message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."**

I don't understand why sometimes this issue happens and sometimes all is working fine.

Analizing the hasplayer code I saw this line into the _BufferController.js_ file:

**// If firefox, set buffer timestampOffset since timestamping (MSE buffer range and <video> currentTime) is based on CTS (and not DTS like in other browsers)
if (isFirefox) {
     buffer.timestampOffset = -getSegmentTimestampOffset(data, request);
}**

I've tried to comment the line and the video plays without the problem.
So I would ask you what does this line do exactly and how can I solve the problem in the right way.

Thanks in advance for your support.
Available for further information.

Ivo

**Comment by bbert** [comment]
Hi,
These lines patch the timestamps for firefox since in Firefox the timestamps returned by MSE buffer timestamps correspond to the media presentation/composition timestamps (CTS/PTS).
While in all other browsers like chrome, MSE buffer timestamps correspond to decoding timestamps (DTS).
See more here: https://github.com/w3c/media-source/issues/54

Can you provide a test stream that fails on firefox?
