### ISSUE TITLE
Working with DVRWindow in MSS live stream

### ISSUE THREAD

**Issue by IcoDeveloper** [Orange-OpenSource/hasplayer.js#232]
When working witjh DVR Window in MSS live stream, I'm having some problems getting back to live position after pausing / repositioning:
`getDVRWindowRange` does not update if the player is paused or if seek to a position within the DVR Window.
I can get it to update to current status by calling `refreshManifest()`; once this finishes, it triggers an event `manifestLoaded`. Adding an EventListener to this event doesn't work for be because it's not specified in MediaPlayer.js in the list of public events. 
Is my workflow for getting back to live after seeking into the DVRWindow reosonable or should I do this some other way?
```
refreshManifest()
manifestLoadedEventReceiver:
 getDVRWindowRange()
seek to range.end   
```

**Comment by IcoDeveloper** [comment]
Just checked: Yes, the Fragmentinfo requests are going out:
```
Debug.js:94 [15:18:45.244][MssFragmentInfoController][audio] Load request  http://streamsrv.icomedias.com/encoders/BoardRoomA/live.isml/Events(2018_4_3_9_2_32)/QualityLevels(64000)/FragmentInfo(audio=94720000000) 
Debug.js:94 [15:18:45.249][MssFragmentInfoController][video] Load request  http://streamsrv.icomedias.com/encoders/BoardRoomA/live.isml/Events(2018_4_3_9_2_32)/QualityLevels(200000)/FragmentInfo(video=94729116666) 
```
However, I'm not seeing any changes to getDVRWindowRange()

**Comment by bbert** [comment]
Do you have a test stream so that we can check this issue?

**Comment by IcoDeveloper** [comment]
`http://icostreaming.streaming.mediaservices.windows.net/d6d20089-230d-480e-96ed-0de539f12948/5749eca8-a9d0-40fd-a36f-3c53f60c25ef.ism/manifest` is currently playing

**Comment by IcoDeveloper** [comment]
Sorry, actually works with the public address  (via azure media services). same stream on Microsoft IIS w/ media extensions:
http://streamsrv.icomedias.com/encoders/BoardRoomA/live.isml/manifest

**Comment by bbert** [comment]
I tested http://icostreaming.streaming.mediaservices.windows.net/d6d20089-230d-480e-96ed-0de539f12948/5749eca8-a9d0-40fd-a36f-3c53f60c25ef.ism/manifest and it works fine.
DVRWindowRange is correctly updated when you do seek or pause.
FYI information, in the Dash-IF sample webapp, the control bar is the browser default one, so it does not reflect DVR window range. You have to implement your control bar.
But you still can anyway check in the console: `mediaPlayer.getDVRWindowRange()`

**Comment by IcoDeveloper** [comment]
I think I got it: 
`<SmoothStreamingMedia MajorVersion="2" MinorVersion="2" Duration="0" TimeScale="10000000" IsLive="TRUE" LookAheadFragmentCount="2" DVRWindowLength="0" CanSeek="TRUE" CanPause="TRUE">`
DVRWindowLength 0 means that DVR is available for the whole recording, i.e. unlimited. Check for manifest.timeShiftBufferDepth > 0 doesn't work and skips updating the window.

**Comment by bbert** [comment]
OK. Indeed we had not yet considered infinite DVR window. It does not seem actually supported.

**Comment by IcoDeveloper** [comment]
I've prepared a patch that allows DVR Window Range to be incremented for infinite size; it uses the "CanSeek" Property from the manifest to differentiate no DVR Window vs. infinite DVR Window.

**Comment by bbert** [comment]
Hi,
Have you checked my review on your PR? Let us know.

**Comment by IcoDeveloper** [comment]
No, haven't seen that. Just checked again and I don't see any reviews on the PR

**Comment by bbert** [comment]
Please look at "Files changed": https://github.com/Orange-OpenSource/hasplayer.js/pull/233/files/e945bc202939111fffc630cb4ced48e76f6ad653

**Comment by IcoDeveloper** [comment]
Sorry, Still don't see anything. No Comments or review show up for me.
![hasplayer_screenshot1](https://user-images.githubusercontent.com/35917998/39292870-b5e062f6-4937-11e8-8a9d-61caa419fd1c.PNG)
![hasplayer_screenshot2](https://user-images.githubusercontent.com/35917998/39292894-c48a736e-4937-11e8-963a-9854af04ec83.PNG)

**Comment by bbert** [comment]
Sorry, my fault, you should see it now

**Comment by vitalist82** [comment]
Hello,

we just have similar issue with this manifest: 

https://dcalivedazn.akamaized.net/13zkofpaetqjl1ei9c57h41iid/tv.ism/Manifest?outlet=dazn-italy&channel=3043&h=af1fa9f9c5689c792a9fb88ede381a6b&plang=en.

DVR Window doesn't update during playback, which prevents us from seeking back to live.

Is the above fix handling the case of live manifests, which don't have DVRWindow attribute and Duration == 0?

Thank you

Tomas

**Comment by vitalist82** [comment]
It seems, that the problem is with checking of presence of `timeShiftBufferDepth` attribute in manifest in `processTfrf` method of `MssFragmentController`. Our live manifests don't contain this value, which means the DVR window range isn't updated. I'm not sure whehter the problem is in the manifest compliance with the specification or if the condition should be removed, which works as a fix for our case.

**Comment by vitalist82** [comment]
Hello, for following live manifests, the fix above doesn't work because of the missing `canSeek` attribute and duration equal to 0: 
https://dcblivedazn.akamaized.net/1h5e7q19g2m5k1wsgvftq4afkq/tv.ism/Manifest?outlet=dazn-jp&channel=1006&h=59fe8353d89362ff497816b2a7349e43&plang=en
https://m2a-dazntest-origin-pool1a.m2amedia.services/channel9002/stream.isml/Manifest

Do you think this is something to be solved on the player level, or should such manifest not be considered as live as it has duration?

**Comment by bbert** [comment]
The manifests you provided are live manifests (IsLive="TRUE" and Duration="0").
So the player handles these streams as live streams.

**Comment by vitalist82** [comment]
but `manifest.timeShiftBufferDepth` is 0 and DVR window is never updated.

**Comment by vitalist82** [comment]
@bbert I'd expect, that the player updates DVR window periodically, so that player.getDVRWindowRange() returns an updated value and after seeking back in the stream and playing for some time it is possible to return back to live position. Current behavior with IE11/Edge is that after seeking back to a position close to live edge, the player throws 'MediaPlayer.seek(): seek value outside available time range'.

**Comment by bbert** [comment]
OK, so it has nothing to do with CanSeek parameter.
I notice that DVRWindowLength field is missing only in the manifest https://dcblivedazn.akamaized.net/sjigh39hytuv193u4n6068wke/tv.ism/Manifest?outlet=dazn-italy&channel=3043&h=c3ecf9c8c8f5b97802e2fd300c2e547b&plang=en
But I can't play this manifest since the stream is protected/encrypted. Can you provide the licenser url?

**Comment by vitalist82** [comment]
The authentication token is sent in the body of the LA request, so the URL won't suffice. The other manifest is a test one, which doesn't use encryption. If you need access to the encrypted stream, I can create a temporary account for you on our staging environment and potentially whitelist your IP.

**Comment by bbert** [comment]
@vitalist82 Indeed, there is an issue when DVRWindowLength field is missing for live streams. Although CanSeek field is missing. Therefore I confirm the DVR window range is never updated.
But what do you expect for the value of DVRWindowLength in this case: Infinity? or segment timeline length?

According to the MSDN specification (https://msdn.microsoft.com/en-us/library/ff469578.aspx), if the DVRWindowLength field is omitted for a live presentation or set to 0, the DVR window is effectively infinite.

**Comment by vitalist82** [comment]
@bbert I think we can stick to the specification and have DVRWindowLength set to Infinity. The main issue in our case was, that after making a seek call to a position close to the end of the stream the player throws an error. This will be resolved after DVR window range will be updated.

**Comment by bbert** [comment]
@vitalist82 Can you try PR #240 and let me know if it solves your issue?

**Comment by vitalist82** [comment]
@bbert it resolves the issue in IE11/Edge. I am going to check with SkyQ STB.

**Comment by vitalist82** [comment]
On SkyQ STB the issue is resolved as well with your PR.
