### ISSUE TITLE
Widevine licencer and post params (DOUBLE call to the licencer)

### ISSUE THREAD

**Issue by pdoria** [Orange-OpenSource/hasplayer.js#238]
Hi,
I'm facing a problem where I need to send a token to the licencer and that token has special characters such as '+'. Was using encodeUriComponent and it works under chrome, linux but fails under Windows and Mac.
The question here is: How can I pass parameters other than in the url (in the body) for a widevine licencer?

What is being done right now:
`laURL: 'https://mydomain.com/widevinedrm?token=' + encodeURIComponent(token)`

EDIT:
I even tried "hacking" hasplayer.js @line 20787 so that I included this:
```
if (protData.extraParams) {
   licenseRequest = protData.extraParams;
}

```
In my stream protData (under widevine) I added 
`extraParams: 'token='+token`

No luck getting the token there although it's being sent in the request payload using the above "hack" :/

EDIT2:
Browsing the network logs it shows that the call to laURL is done *twice* hence breaking the chain (their licencer returns 'reused' and the key is broken)

TIA,
Pedro.

**Comment by bbert** [comment]
Chrome is making twice the request to the licenser since you did not provide the server certificate.
The first request is made by the CDM to get this server certificate (only 2 bytes payload request) to enable VMP.
To get around the token reused issue, then simply provide the server cetificate in input protData for Widevine key system.

Same issue here: https://github.com/Dash-Industry-Forum/dash.js/issues/1924
