### ISSUE TITLE
IE11 crash when user seek to the end

### ISSUE THREAD

**Issue by tbrixi** [Orange-OpenSource/hasplayer.js#243]
Internet Explorer 11 freeze when user seek to the end of VOD file.
Step to reproduce:
1. Open IE11 on Win10x64 (I have build 1803)
2. Navigate to test page http://orange-opensource.github.io/hasplayer.js/1.15.0/samples/Dash-IF/index.html
3. Select MSS > VOD - SuperSpeedway
4. Load
5. Wait for playback and then seek to max right position
6. IE freeze

Issue is on hasplayer from build 1.14.0, build 1.13.0 is OK

Thanks for help

**Comment by tbrixi** [comment]
problem is related to new function "backoffSeekToEnd",
app going to loop and IE11 freeze on:
Stream.js >line 589: setVideoModelCurrentTime.call(this, (duration - backoffSeekToEnd));

**Comment by tbrixi** [comment]
workaround:
global var seekToEnd = false; // to disable going in to loop

if (duration !== Infinity && !seekToEnd && time >= (duration - backoffSeekToEnd)) {
                seekToEnd = true;
                setVideoModelCurrentTime.call(this, (duration - backoffSeekToEnd));
                return;
            } else {
                seekToEnd = false;
            }

**Comment by bbert** [comment]
Hello,
Indeed there is an issue on IE11. I managed to reproduce it.
The initial goal of this part of source code was to enable 'ended' event to be raised on all browsers when one seeks at end of stream.
The solution consisted in seeking 2 seconds (by default) backwards before end of stream, thus enabling video player to playback again and then raising the 'ended' event.
The issue on IE11 comes from the fact that once it has 'seeked' at the new computed position (end - 2s), it raises antoher 'seeking' event with this new position, causing potentially infinite loopback.

To resolve this issue, we simply have to modify the condition when checking if we have to seek backwards end of stream.
Replace:
`if (duration !== Infinity && time >= (duration - backoffSeekToEnd)) {`
by
`if (duration !== Infinity && time > (duration - backoffSeekToEnd)) {`

I am updating your PR with this modification so that you can try on your side.

**Comment by tbrixi** [comment]
working OK, can you merge it to develop?
thanks

**Comment by bbert** [comment]
done
