### ISSUE TITLE
Multiple m3u8 source urls?

### ISSUE THREAD

**Issue by mhassman** [Orange-OpenSource/hasplayer.js#39]
Hi,

Dash.js and html5-video support multiple source urls, but I've been unable to accomplish the same with hasplayer.js. Each .attachSource() triggers a reset().
Anyone have insight?
Thnx!

**Comment by bbert** [comment]
Hi,
As far as I known dash.js does not support m3u8 input manifests since it does only support MPEG DASH.
Do you mean m3u8 manifests in which you can have multiple urls for any variant stream manifest?
Or do you mean multiple/variant urls for the main manifest file that is provided as input of the MediaPlayer.attachSource() method? In this last case, this is up to the webapp to manage those variant input urls.

**Comment by mhassman** [comment]
Hi,
 
Yes, you are correct - dash.js doesn't support m3u8.. I was referncing
dash.js more in the context of a generalized media source extension based
player.
 
As for my intent, I'm more concerned with redundancy. Having the ability to
list multiple source locations for the same manifest. This helps with load
distibution - particularly when utlizing multiple cdn's.
i.e. something like this:
<video>
   <source src="m3u8/mpd-location1" />
   <source src="m3u8/mpd-location2" />
</video>
 
Is there any way to accomplish this with hasplayer.js?
Thnx!
 
 
-Mark


  _____
