### ISSUE TITLE
Linear MSS stream requests not existing fragments

### ISSUE THREAD

**Issue by sprobstCocus** [Orange-OpenSource/hasplayer.js#40]
Hi,

we currently have the issue that sometimes linear streams halt because some fragments could not get loaded. The server responds with HTTP Error "410 - Gone". Comparing the requested fragment with fragments from the manifest one can see that the requested fragment is not found in the manifest. In certain cases the timestamp in the request only differs by 1. For example:
Fragments in Manifest:
`<c t="1427010260251981"/>`
`<c t="1427010280305314"/>`
...
Requested timestamp:
`1427010260251980`

After three consecutive failures, hasplayer gives up and the stream halts. 
We tested mostly in Chrome on different OS.

**Comment by bbert** [comment]
Hi,
Is it a VOD or a live stream?
In case of live streaming, the segments timestamps are provided within the previous segments in a tfrf box. Then the issue can be server-side.

**Comment by sprobstCocus** [comment]
Hello,
We are talking about a live stream.

**Comment by bbert** [comment]
Then there may be some unconformity between timestamps in tfrf boxes and in manifest.
Can you check this point?

**Comment by sprobstCocus** [comment]
Okay, we'll find that out and then come back to you. Thank you.

**Comment by sprobstCocus** [comment]
Hi,

so now the stream was analyzed and we can confirm that the values in the tfrf boxes are correct.
This is a screenshot of the manifest:
![image manifest](https://cloud.githubusercontent.com/assets/12815657/9992927/4b164c5e-6075-11e5-8511-19a4367f72d7.jpeg)

This is a screenshot from the tfrf box analysis:
![tfrf_fragment](https://cloud.githubusercontent.com/assets/12815657/9992960/774e47fe-6075-11e5-9e40-5ca941f8c576.jpeg)

One can see that fragment no: 1438995880142855 is present and should be requested. However the player asks for fragment no: 1438995880142854
I also have a screenshot for that, but I don't think this is needed right now. The Manifest URL in the first screenshot should be publicly available for testing.

**Comment by bbert** [comment]
Hi,
I can confirm what I suspected, i.e. a problem of conformance between what is indicated in the manifest and the content of the tfrf boxes.

Here is a screenshot that illustrates the problem:

![capture](https://cloud.githubusercontent.com/assets/5312520/10041098/eb95e604-61e1-11e5-9eef-2c79095b69ea.png)

The last audio ("audio_aus") segment in the manifest at t = 1440586220409521 has a duration of 20053333.
When you download and parse the preceding segment, at t = 1440586200356188, in the tfrf box you get a different duration, 19626667, for the following segment at t = 1440586220409521.

My conclusion is that the duration of the last segment indicated in the manifest is sometimes wrong, while the durations indicated in the tfrf boxes are correct.

You had a different interpretation in your previous comment, since I think you made a screenshot of the manifest at a different time than the time at which the manifest was downloaded by the player.
