### ISSUE TITLE
Some questions about the player

### ISSUE THREAD

**Issue by adjouhri** [Orange-OpenSource/hasplayer.js#7]
Hi,

I was searching for an HTML 5 player supporting the smooth streaming, and I finally came across your player. My wish is to replace my silverlight player on chrome, that will not be supported in few month : 
http://blog.chromium.org/2014/11/the-final-countdown-for-npapi.html.

I noticed that it is not a final version, and it seems that it's been a long time since you worked on it.

However, I would like to know if It is stable enough to be use in production ?

Are you still working on it, do you plan to do some update ?

If your answer is no on the questions above, do you know another HTML 5 player which support the smooth streaming ?

Thanks a lot in advance for your response.

Regards,
Abel

**Comment by nicosang** [comment]
Hi Abel,

 

We still work on it, and we hope to use it for our services during this year. According to our knowledge, with no drm protection, the last version is quite stable. If you see some problem, say it to us! J

 

Nicolas

 

De : adjouhri [mailto:notifications@github.com] 
Envoyé : mercredi 18 février 2015 17:43
À : Orange-OpenSource/hasplayer.js
Objet : [hasplayer.js] Some questions about the player (#7)

 

Hi,

I was searching for an HTML 5 player supporting the smooth streaming, and I finally came across your player. My wish is to replace my silverlight player on chrome, that will not be supported in few month : 
http://blog.chromium.org/2014/11/the-final-countdown-for-npapi.html.

I noticed that it is not a final version, and it seems that it's been a long time since you worked on it.

However, I would like to know if It is stable enough to be use in production ?

Are you still working on it, do you plan to do some update ?

If your answer is no on the questions above, do you know another HTML 5 player which support the smooth streaming ?

Thanks a lot in advance for your response.

Regards,
Abel
