### ISSUE TITLE
Dijon.js throw an 1061 error on loading the player

### ISSUE THREAD

**Issue by SoleneBuet** [Orange-OpenSource/hasplayer.js#8]
Hi,

I'm testing your hasPlayer framework, and I unfortunately run into the following error upon loading:

```
Error: 1061
    at Object.dijon.System.mapSingleton (dijon.js:300)
    at Object.setup (Context.js:37)
    at Object.setup (DashContext.js:20)
    at Object.dijon.System.injectInto (dijon.js:383)
    at new MediaPlayer (MediaPlayer.js:196)
    at new <anonymous> (main.js:526)
    at d (angular.min.js:34)
    at Object.instantiate (angular.min.js:34)
    at angular.min.js:66
    at angular.min.js:53
```

![capture d ecran 2015-04-02 a 09 58 14](https://cloud.githubusercontent.com/assets/9998409/6960006/d1c4b94a-d91e-11e4-9de5-cf00818483de.png)

Thanks for the help

**Comment by bbert** [comment]
Hi,

This error happens when a class is being mapped but its implementation (.js file) is missing.
Which branch/version are you using?
Which webapp are you using?


De : SoleneBuet [mailto:notifications@github.com]
Envoyé : jeudi 2 avril 2015 09:59
À : Orange-OpenSource/hasplayer.js
Objet : [hasplayer.js] Dijon.js throw an 1061 error on loading the player (#8)


Hi,

I'm testing your hasPlayer framework, and I unfortunately run into the following error upon loading:

Error: 1061

    at Object.dijon.System.mapSingleton (dijon.js:300)

    at Object.setup (Context.js:37)

    at Object.setup (DashContext.js:20)

    at Object.dijon.System.injectInto (dijon.js:383)

    at new MediaPlayer (MediaPlayer.js:196)

    at new <anonymous> (main.js:526)

    at d (angular.min.js:34)

    at Object.instantiate (angular.min.js:34)

    at angular.min.js:66

    at angular.min.js:53

[capture d ecran 2015-04-02 a 09 58 14]<https://cloud.githubusercontent.com/assets/9998409/6960006/d1c4b94a-d91e-11e4-9de5-cf00818483de.png>

Thanks for the help

—
Reply to this email directly or view it on GitHub<https://github.com/Orange-OpenSource/hasplayer.js/issues/8>.

_________________________________________________________________________________________________________________________

Ce message et ses pieces jointes peuvent contenir des informations confidentielles ou privilegiees et ne doivent donc
pas etre diffuses, exploites ou copies sans autorisation. Si vous avez recu ce message par erreur, veuillez le signaler
a l'expediteur et le detruire ainsi que les pieces jointes. Les messages electroniques etant susceptibles d'alteration,
Orange decline toute responsabilite si ce message a ete altere, deforme ou falsifie. Merci.

This message and its attachments may contain confidential or privileged information that may be protected by law;
they should not be distributed, used or copied without authorisation.
If you have received this email in error, please notify the sender and delete this message and its attachments.
As emails may be altered, Orange is not liable for messages that have been modified, changed or falsified.
Thank you.

**Comment by SoleneBuet** [comment]
Hi, 
Thanks for the fast answer.

I'm using the dev one https://github.com/SoleneBuet/hasplayer.js/tree/dash-live-subtitling
Latest commit is a09bd789e9.

I aim to contribute on subtitling as much as possible.

**Comment by bbert** [comment]
Can you merge/rebase your branch with development one and check if the problem resides?

De : SoleneBuet [mailto:notifications@github.com]
Envoyé : jeudi 2 avril 2015 10:09
À : Orange-OpenSource/hasplayer.js
Cc : BERTHELOT Bertrand IMT/OLPS
Objet : Re: [hasplayer.js] Dijon.js throw an 1061 error on loading the player (#8)


Hi,
Thanks for the fast answer.

I'm using the dev one https://github.com/SoleneBuet/hasplayer.js/tree/dash-live-subtitling
Latest commit is a09bd78<https://github.com/Orange-OpenSource/hasplayer.js/commit/a09bd789e939c69b96344d1dcc245b075b6cc888>.

I aim to contribute on subtitling as much as possible.

—
Reply to this email directly or view it on GitHub<https://github.com/Orange-OpenSource/hasplayer.js/issues/8#issuecomment-88812931>.

_________________________________________________________________________________________________________________________

Ce message et ses pieces jointes peuvent contenir des informations confidentielles ou privilegiees et ne doivent donc
pas etre diffuses, exploites ou copies sans autorisation. Si vous avez recu ce message par erreur, veuillez le signaler
a l'expediteur et le detruire ainsi que les pieces jointes. Les messages electroniques etant susceptibles d'alteration,
Orange decline toute responsabilite si ce message a ete altere, deforme ou falsifie. Merci.

This message and its attachments may contain confidential or privileged information that may be protected by law;
they should not be distributed, used or copied without authorisation.
If you have received this email in error, please notify the sender and delete this message and its attachments.
As emails may be altered, Orange is not liable for messages that have been modified, changed or falsified.
Thank you.

**Comment by SoleneBuet** [comment]
I merged, unfortunately not resolving the problem, still this 1061 error.
I also have angular.js.map errors throwing... 
I'm basically using the index.html from the root.

Thanks

**Comment by bbert** [comment]
Please use webapp samples from ‘samples’ folder, for example https://github.com/Orange-OpenSource/hasplayer.js/blob/development/samples/Dash-IF/index.html which uses the context that’s loading MSS/HLS stuff.
The index.html from the root uses the original context from dash.js project and then support only dash.

De : SoleneBuet [mailto:notifications@github.com]
Envoyé : jeudi 2 avril 2015 10:21
À : Orange-OpenSource/hasplayer.js
Cc : BERTHELOT Bertrand IMT/OLPS
Objet : Re: [hasplayer.js] Dijon.js throw an 1061 error on loading the player (#8)


I merged, unfortunately not resolving the problem, still this 1061 error.
I also have angular.js.map errors throwing...
I'm basically using the index.html from the root.

Thanks

—
Reply to this email directly or view it on GitHub<https://github.com/Orange-OpenSource/hasplayer.js/issues/8#issuecomment-88820610>.

_________________________________________________________________________________________________________________________

Ce message et ses pieces jointes peuvent contenir des informations confidentielles ou privilegiees et ne doivent donc
pas etre diffuses, exploites ou copies sans autorisation. Si vous avez recu ce message par erreur, veuillez le signaler
a l'expediteur et le detruire ainsi que les pieces jointes. Les messages electroniques etant susceptibles d'alteration,
Orange decline toute responsabilite si ce message a ete altere, deforme ou falsifie. Merci.

This message and its attachments may contain confidential or privileged information that may be protected by law;
they should not be distributed, used or copied without authorisation.
If you have received this email in error, please notify the sender and delete this message and its attachments.
As emails may be altered, Orange is not liable for messages that have been modified, changed or falsified.
Thank you.

**Comment by SoleneBuet** [comment]
Thanks, now working :-)
