### ISSUE TITLE
change SessionType value in KeySystem

### ISSUE THREAD

**Issue by inbre001** [Orange-OpenSource/hasplayer.js#81]
The Implementation i am currently working on requires the SessionType passed onto the DRM to be changed from temporary to required. 

Is there a way to change the value?

If not i would like to propose to add a sessionType option  to the protectionData Object that can overwrite the sessionType value in the KeySystem_XYZ.js.

Like this: 
```javascript
var cpData = {
'widevine.alpha.com': {
  laURL: 'http://.....',
  pssh: '...',
  sessionType : 'required', // overwrite or at least try first
},
};
```

**Comment by bbert** [comment]
Hi,
Yes, one solution is to add the sessionType field in the protectionData object, and add support for this field in the specific KeySystem implementation that can support other session types that "temporary". For example, in KeySystem_PlayReady.js:
instead of 
<code>sessionType:"temporary",</code>

you could have
<code>sessionType: ((protData && protData.sessionType) ? protData.sessionType : "temporary"</code>

**Comment by inbre001** [comment]
@bbert: Would it be ok to add it to the init function? Like this #84 ?

**Comment by bbert** [comment]
No, like in PR #84 is OK.
I will do the merge.
