### ISSUE TITLE
TTML based subtitles ISOBMFF packaged

### ISSUE THREAD

**Issue by SoleneBuet** [Orange-OpenSource/hasplayer.js#9]
Hi,

I'm currently testing your framework for subtitling with the new EBU-TT-D standard.

I actually seen that you have made a quite nice implementation for TTML based subtitles support, especially with TextTTMLXMLMP4SourceBuffer and so on.

I am trying to get my fragmented subtitles working with your player, but unfortunately, A/V is playing correctly but, CC are not displayed.

I am using content packaged by MP4Box with a dashavc264 profile: 

```
MP4Box -dash 10000 -profile dashavc264:onDemand -rap 
counter_video_720.mp4 
counter_audio.mp4 
subtitles-10m-random-length.mp4 
-out manifest-test-dash-10s-subs-rand-dashavc264
```

With the following MPD:

```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.5.2-DEV-rev99-gb44dfd1-master  on 2015-03-18T09:57:20Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H10M0.00S" maxSegmentDuration="PT0H0M10.00S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011, http://dashif.org/guildelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>manifest-test-dash-10s-subs-rand-dashavc264.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H10M0.00S">
  <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="25" par="16:9" lang="und">
   <Representation id="1" mimeType="video/mp4" codecs="avc1.42c01f" width="1280" height="720" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="514771">
    <BaseURL>counter_video_720_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="872-1623">
      <Initialization range="0-871"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" lang="und">
   <Representation id="2" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="44100" startWithSAP="1" bandwidth="65476">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="1"/>
    <BaseURL>counter_audio_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="748-1511">
      <Initialization range="0-747"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" lang="und">
   <Representation id="3" mimeType="video/mp4" codecs="stpp" startWithSAP="1" bandwidth="1587">
    <BaseURL>subtitles-10m-random-length_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="707-1458">
      <Initialization range="0-706"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```
Thanks for the help.

**Comment by bbert** [comment]
It has been done a long time ago, and we would need to put us back on this subject, but not in the near future.

De : SoleneBuet [mailto:notifications@github.com]
Envoyé : jeudi 2 avril 2015 11:54
À : Orange-OpenSource/hasplayer.js
Cc : BERTHELOT Bertrand IMT/OLPS
Objet : Re: [hasplayer.js] TTML based subtitles ISOBMFF packaged (#9)


Actually, EBU-TT-D is a subset of TTML:
[capture d ecran 2015-03-31 a 11 51 57]<https://cloud.githubusercontent.com/assets/9998409/6961750/5013f310-d92e-11e4-8e70-7036d605bb9d.png>

Yes, Dash.js supports EBU-TT-D as it supports TTML (in MP4 since recently).

Actually I see you removed the profile requirement in the TTMLParser, which lead me to interpret that EBU-TT-D could be easily parsed as any other TTML document.

// ORANGE: The R0008 requirement is removed in the parser implementation to make it work with non-US profiles

Do you have any lead where the blocking could lay?

Thanks

—
Reply to this email directly or view it on GitHub<https://github.com/Orange-OpenSource/hasplayer.js/issues/9#issuecomment-88852946>.

_________________________________________________________________________________________________________________________

Ce message et ses pieces jointes peuvent contenir des informations confidentielles ou privilegiees et ne doivent donc
pas etre diffuses, exploites ou copies sans autorisation. Si vous avez recu ce message par erreur, veuillez le signaler
a l'expediteur et le detruire ainsi que les pieces jointes. Les messages electroniques etant susceptibles d'alteration,
Orange decline toute responsabilite si ce message a ete altere, deforme ou falsifie. Merci.

This message and its attachments may contain confidential or privileged information that may be protected by law;
they should not be distributed, used or copied without authorisation.
If you have received this email in error, please notify the sender and delete this message and its attachments.
As emails may be altered, Orange is not liable for messages that have been modified, changed or falsified.
Thank you.
